[tools]
aws-cli = { version = "latest", symlink_bins = "true" }
gradle = "latest"
java = "17"
oci = "latest"
go = "latest"
rust = "latest"
terraform = "latest"
kotlin = "latest"
android-sdk = "latest"
