[settings]
# This must be enabled to make the hooks work
experimental = true

[tools]
aws-cli = { version = "latest", symlink_bins = "true" }
bat = "latest"
btop = "latest"
chezmoi = "latest"
dotenvx = "latest"
dua = "latest"
dust = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
"github:umlx5h/gtrash" = "latest"
glow = "latest"
go = "latest"
gradle = "8.5"
java = "17"
lazydocker = "latest"
lazygit = "latest"
mkcert = "latest"
node = { version = "lts", postinstall = "corepack enable && corepack install --global pnpm@latest" }
"npm:@dokploy/cli" = "latest"
"npm:@fresh-editor/fresh-editor" = "latest"
"npm:@google/gemini-cli" = "latest"
oci = "latest"
rg = "latest"
ruff = "latest"
rust = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
terraform = "latest"
usage = "latest"
uv = "latest"
yazi = "latest"
yq = "latest"
yt-dlp = "latest"
zoxide = "latest"
age = "latest"
carapace = "latest"
difftastic = "latest"