"$schema" = 'https://starship.rs/config-schema.json'


palette = 'monokai_pro'

format = """
[](red)\
$os\
$username\
[](bg:orange fg:red)\
$directory\
[](bg:yellow fg:orange)\
$git_branch\
$git_status\
[](bg:green fg:yellow)\
$bun\
$nodejs\
$python\
$rust\
$java\
$kotlin\
[](bg:cyan fg:green)\
$container\
$package\
[](bg:purple fg:cyan)\
$cmd_duration\
[](fg:purple)\
$line_break\
$character"""
continuation_prompt = '  '

# Core Module Configurations
[os]
disabled = false
style = "bg:red fg:white"
format = '[$symbol]($style)'

# https://www.nerdfonts.com/cheat-sheet
[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:red fg:black"
style_root = "bg:red fg:black"
format = '[ $user]($style)'

[directory]
style = "bg:orange fg:black"
format = "[ $path ]($style)"
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:yellow fg:black"
format = '[[ $symbol $branch ]($style)]($style)'

[git_status]
style = "bg:yellow fg:black"
format = '[[($all_status$ahead_behind )]($style)]($style)'

# Language Runtimes (grouped by Green background)
[bun]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ]($style)]($style)'
version_format = "${raw}"

[c]
symbol = " "
style = "bg:green fg:black"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'
version_format = "${raw}"

[nodejs]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ]($style)]($style)'
version_format = "${raw}"

[python]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ]($style)]($style)'
version_format = "${raw}"

[rust]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ]($style)]($style)'
version_format = "${raw}"

[java]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ]($style)]($style)'
version_format = "${raw}"

[kotlin]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ]($style)]($style)'
version_format = "${raw}"

[docker_context]
symbol = ""
disabled = true
style = "bg:cyan fg:black"
format = '[[ $symbol ($context) ]($style)]($style)'

[container]
symbol = " "
style = "bg:cyan fg:black"
format = '[[ $symbol \[$name\] ]($style)]($style)'

[package]
symbol = "󰏗"
style = "bg:cyan fg:black"
format = '[[ $symbol ($version) ]($style)]($style)'

[cmd_duration]
show_milliseconds = true
style = "bg:purple fg:black"
format = '[  $duration ]($style)'
show_notifications = true
min_time_to_notify = 15000

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[palettes.monokai_pro]
red = "#FF6188"
orange = "#fc9867"
yellow = "#FFD866"
green = "#A9DC76"
cyan = "#78DCE8"
purple = "#AB9DF2"
white = "#fcfcfa"
black = "#19181a"
grey = "#3e4040"
